### ISSUE TITLE
s8跟着教程跑

### ISSUE THREAD

**Issue by soakit** [k0baya/X-for-serv00#43]
status页面直接就无响应

**Comment by soakit** [comment]
8月初还可以的。

今天看了下就是不行

**Comment by soakit** [comment]
手动去把服务启动，也起不来。

```shell
$ node app.js
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: listen EPERM: operation not permitted 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (node:net:1800:21)
    at listenInCluster (node:net:1865:12)
    at Server.listen (node:net:1953:7)
    at Function.listen (/usr/home/soakit/domains/soakit.serv00.net/public_nodejs/node_modules/express/lib/application.js:635:24)
    at Object.<anonymous> (/usr/home/soakit/domains/soakit.serv00.net/public_nodejs/app.js:235:5)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1844:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EPERM',
  errno: -1,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 3000
}

Node.js v18.20.4
```

试了下，3000端口也不让开。能跑起来的原理是啥，有文档不？

![image](https://github.com/user-attachments/assets/256746af-0ab0-4ab7-b1f1-61d78f1a2502)

**Comment by k0baya** [comment]
原理是使用`Phusion Passenger`。信息太少了，无法判断出了什么问题，我也不知道怎么办。
